### ISSUE TITLE
Can't see any "wakes" only foam

### ISSUE THREAD

**Issue by guerrillacontra** [eliasts/Ocean_Community_Next_Gen#1]
Hi I am not sure if this feature is implemented however, if it is, there are no ship wakes.

Is there a way of providing wake data to the ocean manually otherwise?

**Comment by eliasts** [comment]
Hi.

There is some planning on the next update (which will replace the mesh tiles with a projected grid) to add wakes.

However now you should add it your self by using the getheight functions at specific points and be able to use particle systems, line renderers etc. that adopt to the ocean heights.

**Comment by guerrillacontra** [comment]
Very nice, I will wait for the next update then as I am in no rush.

ps : This project means a lot to me, I have been using Triton (which is not supported any more) and yet to find an Ocean that has a good quality.

This is great!
