### ISSUE TITLE
IndexOutOfRangeException : Ocean.cs

### ISSUE THREAD

**Issue by AntonArmand** [eliasts/Ocean_Community_Next_Gen#14]
Hello ! 

When i run my game, I got an error about the Ocean.cs file
Here is : 

> IndexOutOfRangeException: Index was outside the bounds of the array.
Ocean.GetHeightChoppyAtLocation2 (System.Single x, System.Single y) (at Assets/Ressources/Ocean/Scripts/Ocean.cs:2054)
Buoyancy.update () (at Assets/Ressources/Ocean/Scripts/Buoyancy.cs:157)
Buoyancy.Update () (at Assets/Ressources/Ocean/Scripts/Buoyancy.cs:133)

> 
I'm using your shader since few month, and it's first time i got this error.
So i downloaded the latest version, and exactly the same error ...

I did not change anything on the shader, just added the prefab and ran the game.

The error does not appear all time, if i stop game, retart it few times, it will work few seconds and crash again

**Comment by eliasts** [comment]
Have you copied all the scripts and plugins folder over?
Just adding the prefab is not enough.

**Comment by AntonArmand** [comment]
Yes of course 
<img width="581" alt="fsfsfdsfs" src="https://user-images.githubusercontent.com/34507537/54613161-8aefe380-4a5a-11e9-81f5-bae72b9adaae.png">

**Comment by eliasts** [comment]
In that case please send a project that replicates the issue so I can test it.

**Comment by AntonArmand** [comment]
Just before to send you the project, did i need to also add the folder "Streaming Assets" and files : 
smcs.rsp.meta, smcs.rsp, etc

**Comment by eliasts** [comment]
Better send those also.

**Comment by AntonArmand** [comment]
Ok sorry, my question was, i didn't add this files/folder to my project, could it be the reason why it's not working ? 

I just add them and it's working ^^ No errors so ... ;)

**Comment by eliasts** [comment]
smcs.rsp and gmcs.rsp are needed to allow running of some unsafe code.
This was your issue I think.

**Comment by AntonArmand** [comment]
Ok ok.
I never had this error before, so i thought it couldn't come from this ...

Thanks !
