### ISSUE TITLE
Unity 5.6 shader broken

### ISSUE THREAD

**Issue by andersemil** [eliasts/Ocean_Community_Next_Gen#2]
Hey,

The ocean shaders worked great in 5.5 but since upgrading to unity 5.6.0p4 the specular and reflection has gone completely crazy. Any idea what's going on?

**Comment by eliasts** [comment]
Hi. This is because they changed the zbuffer functionality in the shaders. A new update will come to solve these issues...

**Comment by andersemil** [comment]
Thanks for the reply. Ok this is just weird because the shader code already has some compiler directives to compensate for the Unity 5.5 reversed Z ... but it only seems to apply for the shore lines ... ?

`				//SHORELINES
				#ifdef SHORE_ON
				//UNITY5.5
				#if defined(UNITY_REVERSED_Z)
					float zdepth = 1.0f - LinearEyeDepth (tex2Dproj(_CameraDepthTexture, UNITY_PROJ_COORD(i.ref)).r);
				#else
`

**Comment by eliasts** [comment]
Please try to clean the shader cache and reimport the project. This is how I solved this on unity5.6.0 f3 at least.

**Comment by eliasts** [comment]
The issue is solved with latest update. If you continue to have it please clean the shader cache of the project.
