### ISSUE TITLE
Mobile Performance

### ISSUE THREAD

**Issue by jBachalo** [eliasts/Ocean_Community_Next_Gen#3]
Running the Mobile demo on a top of the line iPad I can get only a maximum of 30fps. Tried targeting Metal, OpenGLES3, no difference.

Are there specific Ocean shader or inspector settings I can tweak to get better performance?

**Comment by eliasts** [comment]
Hi.

I am getting a pure 60 fps on iPhone 5S.
Have you enabled the NATIVE;THREADS preprocessor flags ?

**Comment by jBachalo** [comment]
Thanks! Not that I am aware of. Can I ask how this is done?

**Comment by eliasts** [comment]
In the player setting find the Scripting Define Symbols field:

![untitled](https://user-images.githubusercontent.com/5651523/29485190-7d6f4930-84d6-11e7-9188-046a224f0196.jpg)

**Comment by jBachalo** [comment]
Thanks! will try

**Comment by jBachalo** [comment]
Sorry no difference. I am targeting Metal IL2CPP. Can you suggest some other setting I might try?

![player_othersettings](https://user-images.githubusercontent.com/247784/29528272-741489a6-8669-11e7-91b8-284495cf7c93.png)

**Comment by eliasts** [comment]
Hi.

I haven't tested it on Metal. Try it on OpenGL ES 2 or 3.
