### ISSUE TITLE
How to update the old ocean project

### ISSUE THREAD

**Issue by tunaguralp** [eliasts/Ocean_Community_Next_Gen#4]
I have already used before your project. First of all awesome job thank you very much for that. Now I see you updated the project but how can i extract old one and use new? Also in my project "ocean" folder a little bit in a mess :))

**Comment by eliasts** [comment]
Hello.

Just download the project copy all the files and replace them in your project.

Alternatively download the project in a new project and create a unity package with all the dependencies, and then import it to your project.

**Comment by tunaguralp** [comment]
Yeah, I have done like your suggestion but after you write I checked again and I realized my unity version was old :D. Now everything is ok thank you :)
