### ISSUE TITLE
Ocean flickers when using in VR

### ISSUE THREAD

**Issue by unknownMarty** [eliasts/Ocean_Community_Next_Gen#6]
Hi, 

I'm using the ocean in VR. When I enable reflection the ocean starts to flicker during runtime and editor  is more visible.  It's related to the skybox. When I upped the refresh frame.

**Comment by ghost** [comment]
Hi,
Can you send me a SS please?
unknownMarty <notifications@github.com>, 8 Ağu 2018 Çar, 16:00 tarihinde
şunu yazdı:

**Comment by unknownMarty** [comment]
Here's an video of the issue: https://vimeo.com/284125469

**Comment by unknownMarty** [comment]
Solved it by changing `Camera cam = Camera.current` to `Camera cam = Camera.main` in function `RenderReflectionAndRefraction()` . I saw that the fieldOfView where set of the editor camera (65 degrees) and not the VR camera (110.0266 degrees)

**Comment by eliasts** [comment]
ok good to know!

**Comment by unknownMarty** [comment]
Shall i create a pull request with the fix?

**Comment by ShadowTeolog** [comment]
reflection texture render not every frame,this result flicker than reflection textures from different cameras is exchanging.  this kind of trouble can be fixed by set reflection to generate every frame. At least for my 3 cameras.

**Comment by minusplusminus** [comment]
True, but that has an performance impact.
