### ISSUE TITLE
Latest XR commit 2f99210 breaks Unity5

### ISSUE THREAD

**Issue by twobob** [eliasts/Ocean_Community_Next_Gen#9]
I shoved the no-brainer conditional compilation fix as a comment on the commit.
https://github.com/eliasts/Ocean_Community_Next_Gen/commit/2f9921092d583ab0884b6466a049f73b8caed8f4#diff-0e74e5304ecc41831c7756ff582ad7ea
Hope it helps

**Comment by eliasts** [comment]
Hello.

Sorry for your issue and thanks for the advice.
This was a pull request.

**Comment by eliasts** [comment]
It should be ok now.
